//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una fecha..
        /// </summary>
        internal static string ClientDataTypeModelValidatorProvider_FieldMustBeDate {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser un número..
        /// </summary>
        internal static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no puede ser blanco o null..
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} no es válido..
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una dirección de email válida..
        /// </summary>
        internal static string EmailAttribute_ValidationError {
            get {
                return ResourceManager.GetString("EmailAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una fecha y encontrarse entre los valores {1:d} y {2:d}..
        /// </summary>
        internal static string FechaAttribute_ValidationError {
            get {
                return ResourceManager.GetString("FechaAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email o Password no válido..
        /// </summary>
        internal static string MembershipStatus_BAD_PASSWORD {
            get {
                return ResourceManager.GetString("MembershipStatus_BAD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario creado con el DNI ingresado..
        /// </summary>
        internal static string MembershipStatus_DUPLICATED_USER {
            get {
                return ResourceManager.GetString("MembershipStatus_DUPLICATED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Email ingresado ya se encuentra registrado..
        /// </summary>
        internal static string MembershipStatus_DUPLICATED_USER_MAIL {
            get {
                return ResourceManager.GetString("MembershipStatus_DUPLICATED_USER_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su token ha expirado, por favor solicite un nuevo reinicio de clave..
        /// </summary>
        internal static string MembershipStatus_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("MembershipStatus_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ha sido creado satisfactoriamente..
        /// </summary>
        internal static string MembershipStatus_USER_CREATED {
            get {
                return ResourceManager.GetString("MembershipStatus_USER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario con el mail ingresado..
        /// </summary>
        internal static string MembershipStatus_USER_FOUND {
            get {
                return ResourceManager.GetString("MembershipStatus_USER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario se encuentra bloqueado..
        /// </summary>
        internal static string MembershipStatus_USER_LOCKED {
            get {
                return ResourceManager.GetString("MembershipStatus_USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado..
        /// </summary>
        internal static string MembershipStatus_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("MembershipStatus_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una cadena de texto con una longitud mínima de {1}..
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es inválido..
        /// </summary>
        internal static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido..
        /// </summary>
        internal static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe encontrarse entre los valores {1} y {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe validar la siguiente expresión regular &apos;{1}&apos;..
        /// </summary>
        internal static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido..
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una cadena de texto con una longitud máxima de {1}..
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe ser una cadena de texto con una longitud mínima de {2} y máxima de {1}..
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no es válido..
        /// </summary>
        internal static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
    }
}
